name: CI-CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checks out the current git commit so we can use it.
      # read more at https://github.com/orgs/community/discussions/25682
      - uses: actions/checkout@v2

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Test everything
        run: npm run test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
