name: CI-CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checks out the current git commit so we can use it.
      # read more at https://github.com/orgs/community/discussions/25682
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Write your CI workflow here!"

      - name: Install deps
        run: npm install

      - name: Test everything
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy
